### ISSUE TITLE
KODI 15.2 BUG DVD MENU

### ISSUE THREAD

**Issue by Gabullito** [mdeguzis/SteamOS-Tools#107]
Some DVD menu is not displayed (just a black screen ) , this bug only on DVDs that have a second menu after "start movie" while it works correctly on ubuntu release

sorry for my English
#### Progress Tracker (Please do not remove)
- [x] Investigate issue
- [ ] Fix committed / Resolution

**Comment by ProfessorKaos64** [comment]
Np on your English :+1: This may be hard to reproduce. What I _can_ tell you, is that the Kodi source code is built using "official" packaging means, but done so natively on SteamOS systems at build time (when the package is created). I do have a fair bit of movies, and depending on the movie and price, maybe I'll buy this title you have trouble with. Can you tell me a few titles, or at least one, so I may try to reproduce this error?

**Comment by Gabullito** [comment]
I have this problem with :
http://www.amazon.fr/Schtroumpfs-DVD-Copie-digitale/dp/B00E94HLFA/ref=sr_1_1/275-6992171-9443201?ie=UTF8&qid=1450501751&sr=8-1&keywords=schtroumpfs+2

http://www.amazon.fr/Engrenages-Saison-4-Caroline-Proust/dp/B008JELN78/ref=sr_1_5?ie=UTF8&qid=1450502132&sr=8-5&keywords=engrenages

Cordialy

**Comment by ProfessorKaos64** [comment]
@Gabullito , Kodi 16 Jarvis is released into the repository. Please retest.

**Comment by Gabullito** [comment]
Hello,
i retested with Jarvis i have same problem
cordialy

**Comment by ProfessorKaos64** [comment]
I thought about this, I wonder if this has to do with the custom compositor not allowing the 2nd window to manifest itself. Can you try opening Kodi in desktop mode and attempting to reproduce this behavior?
