### ISSUE TITLE
KODI 15.2 BUG EJECT CD

### ISSUE THREAD

**Issue by Gabullito** [mdeguzis/SteamOS-Tools#108]
"EJECT CD " not work in kodi 15.2 while work perfectly on desktop
#### Progress Tracker (Please do not remove)
- [x] Investigate issue
- [ ] Fix committed / Resolution

**Comment by ProfessorKaos64** [comment]
If it works perfectly on the desktop, could be that the steam does not have access to the optical group. I'll take a look at this today or tomorrow.

**Comment by ProfessorKaos64** [comment]
This likely also has something to do with how optical media does not automount during steamos-session, what you are running games on. In desktop mode it does. The only thing in BPM that seems to automount is USB devices, via the 'usbmount' package. This may be an OS issue, not entirely in my control. I'll continue to look at it. If you  have to get up to put a disc in, i'd imagine it's not a hassle to just press the button? If you have a drive that auto feeds with no tray, `eject` and `eject -t` will open/close the "tray" respectively.

**Comment by Gabullito** [comment]
Thank you for response , but is not a problem to get up and press the button .
I just wanted to report bug

Best regards

**Comment by ProfessorKaos64** [comment]
@Gabullito , Kodi 16 Jarvis is released into the repository. Please retest.

**Comment by Gabullito** [comment]
Hello,
i retested with Jarvis  i have same problem
cordialy
