### ISSUE TITLE
Feature Request slackware

### ISSUE THREAD

**Issue by MachinaeWolf** [mdeguzis/SteamOS-Tools#134]
build-test-chroot.sh -type steamos outputs
==ERROR==
Linux host distribution not supported for building this chroot

--------- Progress tracker - do not edit below this line --------- 
- [x] Install Slackware on VM 
- [ ] investigate script requirements under Slackware

**Comment by ProfessorKaos64** [comment]
Installing Slackware tonight.

**Comment by ProfessorKaos64** [comment]
Should be able to look at this soon this week.

**Comment by ProfessorKaos64** [comment]
I did not forget about this, sorry, I got distracted, hope to get to this soon enough.

**Comment by MarioMaster100** [comment]
No rush I got my steam issue sorted on slackware, but I can still test your chroot tool for you.
