### ISSUE TITLE
[Package Request] Moar emulators! Moar software! Much wow.

### ISSUE THREAD

**Issue by mdeguzis** [mdeguzis/SteamOS-Tools#143]
#### Please describe your issue in as much detail as possible:

Ekianjo is requesting some more emulators.
#### Emulator list / software request list

A good list is available via www.zophar.net/linux
- [x] innoextract (for GOG) - Already available in Debian repos.
- [x] Amiga emulator - (FS-UAE) - Already available in Debian repos.
- [x] NES emulator (nestopia) -  Already available in Debian repos.
- [x] SNES emulator (zsnes) -  Already available in Debian repos.
- [x] Genesis emulator (dgen)  -  Already available in Debian repos.
- [ ] 3DO Emulator (FreeDO) - difficult to do , see [here](http://www.linuxquestions.org/questions/general-10/finally-only-working-3do-emulator-has-gone-oss-843789/). Only the [core](https://github.com/darvin/freedo) is available, not the emulator.
- [x] Atari ST (Hatari)  -  Already available in Debian repos.
- [x] Sega Master System (dgen)  -  Already available in Debian repos.
- [x] NEC consoles (Mednafen (cli) HuGo! (GUI) ) - Already available in Debian repos. Hu-Go! uploaded to brewmaster_testing
- [x] PS1 (PCSX (Mednafen works fine, pcsxr already in Debian repos)
- [x] DOSBox  -  Already available in Debian repos.
- [x] ScummVM  -  Already available in Debian repos.
- [x] Sega Saturn (Yabause)  -  Already available in Debian repos.
- [x] Dreamcast (Reicast) - uploaded to brewmaster_testing for evaluation
- [x] Arcade Emulators (MAME)  -  Already available in Debian repos.
#### Wiki Documentation
- [x] Configuration of controllers under WINE / POL
#### Progress Tracker (Please do not remove)
- [x] Investigate emulators
- [x] Investigate WINE controller configuration options / documentation
- [x] Gather source code for each emulator (preferably GitHub)
- [x] Fix committed / Resolution

**Comment by ekianjo** [comment]
FS-UAE is an Amiga Emulator but there are probably a couple more options. Not sure if UAE4ALL has a x86 version. 

NES -> nesticle maybe ? 
SNES -> Snes9x ? 
Genesis -> Picodrive would be nice

Other to add: 
- 3DO Emulator (3doh)
- Atari ST (Hatari)
- Sega Master System (forgot the name of the most used one)
- NEC consoles
- PS1 (PCSX)
- DOSBox
- ScummVM
- Sega Saturn (Yabause)
- Dreamcast (Reicast)
- Arcade Emulators (MAME)

**Comment by ProfessorKaos64** [comment]
Updated list. I'll chip away at this when I have time. This will take some time. I haven't checked the Debian repositories yet on available emualtors either.

**Comment by ProfessorKaos64** [comment]
There is a wiki entry for WINE and controller input already:

https://github.com/ProfessorKaos64/SteamOS-Tools/wiki/Configuring-Controller-Input-Under-Wine

**Comment by ekianjo** [comment]
to add as well: 
ZDoom
ResidualVM
Exult
OpenRA
Dune Dynasty

**Comment by ProfessorKaos64** [comment]
Individual packages for games of probably have a request for each since they may require a bit of work. Make sure to check the Debian repos first as well.  I think openra is there. In any case this is a very tall order. It will take a while.

**Comment by ekianjo** [comment]
For 3DO I would recommend 3doh - see github

**Comment by ekianjo** [comment]
One quick comment, the problems with debian repos for emulators is that they usually have completely outdated versions of such emus. Those without too much dependencies should be compiled to their latest versions in an ideal world.

**Comment by ProfessorKaos64** [comment]
I only cut into existing packages in the Debian repos if they are that* bad. The less I have to maintain, the better. Do you have a GitHub link for 3doh, or the most up to date source code link? I would ask that individual requests be put in for those cases, with justification why the Debian version is insufficient.

**Comment by ekianjo** [comment]
Here is 3doh : https://github.com/r-type/libretro-3doh (the original code on google code is also linked).

**Comment by ProfessorKaos64** [comment]
There is no source code at the Google Code link.

**Comment by ekianjo** [comment]
here you go
https://github.com/Tallefer/3doh

**Comment by ProfessorKaos64** [comment]
Have you ever compiled that successfully?

**Comment by ekianjo** [comment]
Yup. You have to change the options in the makefile to make it compile, and then it was no issue for video.o -

**Comment by ProfessorKaos64** [comment]
Ill take a peak at your fork of it then. I will still package the more modern binary of Phoenix.  See: http://www.emucr.com/2016/04/phoenix-v25.html?showComment=1471907729763&m=1#c8558160200499564731

**Comment by ProfessorKaos64** [comment]
What did you change in the Makefile? 

On August 22, 2016 7:25:12 PM EDT, ekianjo <notifications@github.com> wrote:
>Yup. You have to change the options in the makefile to make it compile,
>and then it was no issue for video.o - 
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/ProfessorKaos64/SteamOS-Tools/issues/143#issuecomment-241581613

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ekianjo** [comment]
I'll have to look at it again (dont have time right now, going to work soon), but at that time I remember I had to change some flags to make it compile on ARM. I will take a look during the day.

**Comment by ProfessorKaos64** [comment]
I got it working by using make -f makefile.gl in a 32 bit chroot with 32 packages. I see there is a flag for that too.

**Comment by Enigma0** [comment]
What about Dolphin?

- https://wiki.dolphin-emu.org/index.php?title=Installing_Dolphin#Ubuntu
- https://wiki.dolphin-emu.org/index.php?title=Building_Dolphin_on_Linux

**Comment by ProfessorKaos64** [comment]
Please check the [repository](https://github.com/ProfessorKaos64/SteamOS-Tools/wiki/SteamOS-Tools-Repository) first. dolphin-emu (stable) and dolphin-emu-master (rolling) are already available. If one is not, you can submit a separate request.

**Comment by ProfessorKaos64** [comment]
Unless I or @ekianjo can fix the Makefile/project for 3doh, I am going to likely just test/include the binaries/project for Phoenix. I could try hacking together a package from the libretro port of 4do (maybe?).

**Comment by ProfessorKaos64** [comment]
phoenix-emu works, but it's all in Russian :/
