### ISSUE TITLE
[ Request ] A NCurses Interface to Rule Them All

### ISSUE THREAD

**Issue by ekianjo** [mdeguzis/SteamOS-Tools#144]
Scripts are nice and all, but keeping things user-friendly should be a priority to have more folks consider SteamOS as a cool platform. We should try to create a ncurse menu that can make it super easy and quick to do most actions, such as 
- adding the repositories
- updating the repositories or running a git pull on the SteamOS-Tools
- adding your GOG information (to be used by lgogdownloader)
- downloading GOG games and auto-extracting them and creating all relevant shortcuts automatically
- installing all relevant emulators in one click (or at least letting one select what emulators to install)
- installing all relevant software in one click (Kodi, Steam for Wine, Playonlinux, etc...) kind of what most folks would want anyway. 

All of the above is relatively trivial to implement. We just need to get started on it.

**Comment by ProfessorKaos64** [comment]
I did have this, and have (but no a complete list) via ./desktop-sofware.

See: 

* [line number](https://github.com/ProfessorKaos64/SteamOS-Tools/blob/brewmaster/desktop-software.sh#L370)
* [list of packages from the emulators parameter](https://github.com/ProfessorKaos64/SteamOS-Tools/blob/brewmaster/cfgs/software-lists/emulators.txt)

```
./desktop-software.sh install emulators
```

**Comment by ProfessorKaos64** [comment]
I used to dialog a bit. Any other recommendations? I'm not opposed to this for common item.

**Comment by ProfessorKaos64** [comment]
I will be working on a dialog-based script tool to pool all of the smaller pieces together. Since dialog is only found within Debian's repositories, it will be downloaded as a prereq.
