### ISSUE TITLE
[Package Request] Kodi 17 Stable Release

### ISSUE THREAD

**Issue by LePresidente** [mdeguzis/SteamOS-Tools#161]
Kodi 17 is now the new stable release, Can the package be added 

Source: [kodi.tv](https://kodi.tv/)

#### Progress Tracker (Please do not remove)

- [x] Investigate issue
- [ ] Fix committed
- [ ] Confirmed Resolution

**Comment by mdeguzis** [comment]
Sweet, didn't know this was out. I will get to this tonight.

**Comment by mdeguzis** [comment]
syncing to package pool now.

**Comment by LePresidente** [comment]
Gonna reopen this there are dependencies missing

`desktop@steamos:~/SteamOS-Tools$ sudo apt install kodi-bin
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 kodi-bin : Depends: libva1 (>= 1.7.3) but 1.4.1-1+steamos1+bsos1 is to be installed
E: Unable to correct problems, you have held broken packages.
desktop@steamos:~/SteamOS-Tools$`

**Comment by mdeguzis** [comment]
Checking this out soon.

**Comment by mdeguzis** [comment]
The problem here is Valve provides a lower version of libva1. Package pinning for SteamOS-Tools follows a strict guideline not to overwrite Valve's packages. A simulated install of my libva1 looks like this:

```
desktop@steamos:~$ apt-get --simulate install libva1=1.7.3-2~bsos+1
NOTE: This is only a simulation!
      apt-get needs root privileges for real execution.
      Keep also in mind that locking is deactivated,
      so don't depend on the relevance to the real current situation!
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  amdgpu-pro-lib32:i386 amdgpu-pro-vulkan-driver:i386
  libatiadlxx-amdgpu-pro:i386 libdrm-amdgpu-pro-amdgpu1:i386
  libdrm2-amdgpu-pro:i386 libegl1-amdgpu-pro:i386 libgbm1-amdgpu-pro:i386
  libgl1-amdgpu-pro-dri:i386 libgl1-amdgpu-pro-glx:i386
  libgles2-amdgpu-pro:i386 libssl1.0.0:i386 libvdpau-amdgpu-pro:i386
Use 'apt-get autoremove' to remove them.
The following packages will be REMOVED:
  i965-va-driver:i386 libva1:i386 steamos-packages:i386
The following packages will be upgraded:
  libva1
1 upgraded, 0 newly installed, 3 to remove and 148 not upgraded.
Remv steamos-packages:i386 [2.0+bsos1]
Remv i965-va-driver:i386 [1.4.1-2+steamos1+bsos1]
Remv libva1:i386 [1.4.1-1+steamos1+bsos1]
Inst libva1 [1.4.1-1+steamos1+bsos1] (1.7.3-2~bsos+1 Custom SteamOS-Tools Debian Repository:packages.libregeek.org [amd64])
Conf libva1 (1.7.3-2~bsos+1 Custom SteamOS-Tools Debian Repository:packages.libregeek.org [amd64])
```

You can force the installation by running:

```
sudo apt-get install libva1=1.7.3-2~bsos+1
```

It doesn't matter if I specify the exact version int he package control field, since Valve's packages supersede it. I'm not sure if I will just make an exception for libva1 or not.

**Comment by mdeguzis** [comment]
I'll see if this gets any traction:

https://github.com/ValveSoftware/SteamOS/issues/585

**Comment by mdeguzis** [comment]
Upstream issue resolved.
