### ISSUE TITLE
kodi-inputstream-adaptive package missing in repository

### ISSUE THREAD

**Issue by Juppstein** [mdeguzis/SteamOS-Tools#163]
#### Your system information

* Steam client version: 1486690646
* SteamOS version: 2.0 u 2.110
* Opted into Steam client beta?: [Yes] 
* Opted into SteamOS beta?: [Yes] 
* Have you checked for updates in Settings > System?: [Yes]

#### Please describe your issue in as much detail as possible:
Looks like the kodi-inputstream-adaptive package is missing in the repository as a package. This package is required to allow addons like the Youtube addon to work properly in Kodi v17 if you want the addon to support 1080p resolutions and up and solve some issues with mpeg-dash videos.
#### Steps for reproducing this issue:

1. Install youtube addon without inputstream-adaptive package
2. Try to open some high res youtube videos
3. Rotating circles appear for about 20 seconds
4. Error message appears that some items could not be opened.

#### Progress Tracker (Please do not remove)

- [x] Investigate issue
- [x] Fix committed
- [ ] Confirmed Resolution

**Comment by mdeguzis** [comment]
Got it, i'll try to get to this tonight. If not, def. tomorrow.

**Comment by mdeguzis** [comment]
I will be away this weekend, returning Sunday evening, ~20:00 UTC-5. Sorry for the delay.

**Comment by mdeguzis** [comment]
Uploaded:

```
kodi-inputstream-adaptive_1.0.6+git+bsos_amd64.deb
kodi-inputstream-adaptive-dbg_1.0.6+git+bsos_amd64.deb
```

Please retest.

**Comment by Juppstein** [comment]
Works as intended so far!

**Comment by Juppstein** [comment]
Hi. But the inputstream addon still would need to be updated as well :) as mentioned in issue 162, which broke the addon during fixing the PVR addon.

**Comment by mdeguzis** [comment]
I forgot to update kodi-inputstream-adaptive? or which one?

**Comment by Juppstein** [comment]
Yup, that's the one :)

**Comment by mdeguzis** [comment]
What package are you missing? I updated the packages below on 2017-02-20.

```
mikeyd@archboxmtd steamos-tools $ reprepro list brewmaster | grep kodi-inputstream-adaptive
brewmaster|main|amd64: kodi-inputstream-adaptive 1.0.6+git+bsos
brewmaster|main|amd64: kodi-inputstream-adaptive-dbg 1.0.6+git+bsos
brewmaster|main|source: kodi-inputstream-adaptive 1.0.6+git+bsos
```

**Comment by Juppstein** [comment]
I think the problem is similar to the issue you had when you compiled the pvr plugin back then before Wsnipex gave some hints about how to fix it in issue #162 . While the package is there, Kodi is not able to get it somehow and throws an error each time it starts:

`18:21:22.068 T:139703169132608   ERROR: ADDON: Could not locate inputstream.adaptive.so.1.0.6`

**Comment by mdeguzis** [comment]
ah, that's right. got it, will update tonight.

**Comment by mdeguzis** [comment]
sorry I got distracted, and now sick bleugh... I haven't forgotten this. Can easily update this in a few hours.

**Comment by Juppstein** [comment]
Get well first :)

**Comment by mdeguzis** [comment]
Try now

**Comment by Juppstein** [comment]
Looks good. I do not see any error regarding this addon in the logs and the videos load correctly with the right resolution.
