### ISSUE TITLE
Kodi

### ISSUE THREAD

**Issue by Sandmanu** [mdeguzis/SteamOS-Tools#165]
#### Your system information

* Steam client version:
* SteamOS version: 2.0 brewmaster 1.2.98
* Opted into Steam client beta?: [Yes/No] 
* Opted into SteamOS beta?: [Yes/No]  no
* Have you checked for updates in Settings > System?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen.

Following the instructions for installing Kodi (https://github.com/mdeguzis/SteamOS-Tools/wiki/Kodi), including the tools and packages (both of which appear on desktop), however, there is no kodi file in the packages (cd SteamOS-Tools-Packaging/kodi) and sudo apt-get install kodi results in:
       desktop@steamos:~$ sudo apt-get install kodi
       Reading package lists... Done
       Building dependency tree       
       Reading state information... Done
       Some packages could not be installed. This may mean that you have
       requested an impossible situation or if you are using the unstable
      distribution that some required packages have not yet been created
      or been moved out of Incoming.
     The following information may help to resolve the situation:

     The following packages have unmet dependencies:
      kodi : Depends: kodi-bin (>= 16.1+dfsg1-2~bpo8+1) but it is not going to be installed
        Depends: kodi-bin (< 16.1+dfsg1-2~bpo8+1.1~) but it is not going to be installed
      E: Unable to correct problems, you have held broken packages.

Both SteamOS Tools and Steam OS Tools-Packaging loaded properly from the Terminal, just no Kodi. Removed? Broken? Other?

What are we missing/needs update?

#### Steps for reproducing this issue:

1. 
2. 
3. 

#### Progress Tracker (Please do not remove)

- [x] Investigate issue
- [ ] Fix committed
- [ ] Confirmed Resolution

**Comment by mdeguzis** [comment]
See: https://github.com/mdeguzis/SteamOS-Tools/issues/161.

**Comment by Sandmanu** [comment]
It looks like you're saying that forcing the update on the libva1 file will
allow the current version of Kodi to load in.

When using your line from #161, this is the result:

desktop@steamos:~$ sudo apt-get install libva1=1.7.3-2~bsos+1
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Version '1.7.3-2~bsos+1' for 'libva1' was not found

So either my version of Steam (newest? it was installed over the weekend)
isn't supporting this or I'm not pointed to the right place to pull the
correct files. I'm not concerned with latest and greatest Kodi, 15 would be
just fine for what I intend to use it for, so what's the workaround?

thanks

**Comment by mdeguzis** [comment]
You should be seeing Kodi 17. I suggest running a repair on your sources:

```
cd SteamOS-Tools
git pull
./configure-repos.sh --repair
apt-cache policy show kodi
```

**Comment by Sandmanu** [comment]
repair did the job to make Kodi load in.

Thanks for your quick response.

**Comment by mdeguzis** [comment]
np, I typically respond/react when I have time.
