### ISSUE TITLE
Kodi Krypton Downgrade Path

### ISSUE THREAD

**Issue by Sandmanu** [mdeguzis/SteamOS-Tools#166]
#### Your system information 

* Steam client version: 
* SteamOS version: 2.0 brewmaster 1.2.98
* Opted into Steam client beta?: [Yes/No] 
* Opted into SteamOS beta?: [Yes/No]  no
* Have you checked for updates in Settings > System?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:

This issue begins with a Kodi Krypton issue reading DVD file structures, which is not a problem I seek an answer for here. 

What I do need an answer for is the path to follow to revert back to previous versions of Kodi when using your script. sudo apt-get install kodi properly loads Krypton/latest version, but the naming conventions used by the Kodi wiki for downgrade don't work, so where do we need to point or what needs to be added to pull previous versions with your script?

Thanks.

#### Progress Tracker (Please do not remove)

- [ ] Investigate issue
- [ ] Fix committed
- [ ] Confirmed Resolution

**Comment by mdeguzis** [comment]
I only provide the current stable release, with betas/alphas/rc in the unstable repo. There are far too many packages to offer multiple versions, ans way too many things that could go wrong with having to juggle all those variables. You could pin kodi in the preferences file for the Debian repo under /etc/apt/preferences.d/, and install their version specially.

If you mean something else, please provide the source URL of the documentation you speak of.

**Comment by Sandmanu** [comment]
From the Kodi Wiki ( http://kodi.wiki/view/HOW-TO:Install_Kodi_for_Linux#Downgrading_between_newer_and_older_stable_versions ) when following their code, brewmaster is stepping over it to install kodi 17.

I did ( sudo apt-get install software-properties-common ) so that I could use their add-apt-repository command and that did seem to work fine although that command did not write to the etc/apt/sources.list file. I used nano to edit it, dropped in deb https://launchpad.net/~team-xbmc/+archive/ppa above your links, that threw an error.

How do I get around this to bypass the auto call to Krypton? (or if you know how to make it read  the ifo files in a dvd folder from the library menu, like it does in LE, here in Steam, I'd keep 17..again, not your issue..but if you know..lol).

**Comment by mdeguzis** [comment]
That is a PPA, which has different stored versions, as they maintain stable/testing/etc... PPAs. I do not maintain that. This is not supported under my repo. I unfortunately do not have time to maintain that and deal with any issues that come up when I do this project by myself. I do not know of any workarounds for the DVD issue, but I don't mind checking.
