### ISSUE TITLE
Package lists at packages.libregeek.org practically empty

### ISSUE THREAD

**Issue by oolongbrothers** [mdeguzis/SteamOS-Tools#167]
Hi!

during the last week I, the steamos-tools apt repo has been practically empty. I was unsure if that had anything to do with the monthly bandwidth limit that you warned about in the wiki, so I waited until the start of May, but so far the issue has not rectified itself.
Here the directory listing from http://packages.libregeek.org/steamos-tools/package_lists/
```
      Parent Directory                                  -   folder or file
      binary-no-source.txt         24-Apr-2017 20:04    0   Text file
      brewmaster-testing_games.txt 24-Apr-2017 20:04    0   Text file
      brewmaster-testing_kodi.txt  24-Apr-2017 20:04    0   Text file
      brewmaster-testing_main.txt  24-Apr-2017 20:04    0   Text file
      brewmaster-testing_qt.txt    24-Apr-2017 20:04    0   Text file
      brewmaster_games.txt         24-Apr-2017 20:04  115   Text file
      brewmaster_main.txt          24-Apr-2017 20:04  273   Text file
      orphaned-cruft.txt           24-Apr-2017 20:04    0   Text file
      source-no-binary.txt         24-Apr-2017 20:04    0   Text file
```

Note the time stamp of the latest update being `24-Apr-2017 20:04`, which about coincides with my perception of the problem first appearing. 

I understand that this project is in a bit of a hiatus. Just wanted you to know that there are people out there who greatly appreciate your work - even ones that only recently discovered it, like me.
Even if you were to shut down the repo today, I would be deeply thankful as to all the solutions you have led me to for my little console. I just sent a PayPal donation to at least offset your bandwidth costs a little.

#### Steps for reproducing this issue:

1. Go to http://packages.libregeek.org/steamos-tools/
2. Check any of the `package_lists/*.txt files`
3. See that they are empty except for a few leftover packages

#### Progress Tracker (Please do not remove)

- [x] Investigate issue
- [x] Fix committed
- [ ] Confirmed Resolution

**Comment by mdeguzis** [comment]
I wouldn't say it's on hiatus (I am the only maintainer, mind you). I am just more busy now, so I mainly update packages as I notice updates (e.g. RetroArch), or rely on user requests now more than before. I did see the donation, so that was you? Thank you immensely to help pay that bill for my server. I will check out this issue when I return home from work.

Many thanks,

-PK

**Comment by oolongbrothers** [comment]
Sorry, my fault, good to hear that the project is alive.
Yeah, I saw the debs in place in the pool, so hopefully easy to fix the package lists.
Greatly appreciated.

Cheers!
//oO

**Comment by mdeguzis** [comment]
My database meta data is screwed, and my incremental backup didn't cover that date I think it happened. Doing some recovery steps so I can avoid wiping things.

**Comment by mdeguzis** [comment]
I think I was able to recover the regular brewmaster pool. I'll have to rebuild the list of unreferenced brewmaster-testing files (which if the former is ok, that is not the worst). Could be worse. Got some work to do for sure. I'll just have to keep an eye on my bandwidth cap for the month.

**Comment by mdeguzis** [comment]
I was able to rebuild most of the package db and inclusion of the debs (as the dsc was registered after repair, or was) by picking a list from 2 weeks ago of pacakges, and feeding that in a loop:

```
for f in `cat package_lists/brewmaster_main.txt | cut -d " " -f 2`; do find pool -name "$f*.deb" -exec reprepro includedeb brewmaster {} \;; done

for f in `cat package_lists/brewmaster_games.txt | cut -d " " -f 2`; do find pool -name "$f*.deb" -exec reprepro includedeb brewmaster {} \;; done

for f in `cat package_lists/brewmaster-testing_main.txt | cut -d " " -f 2`; do find pool -name "$f*.deb" -exec reprepro includedeb brewmaster-testing {} \;; done

for f in `cat package_lists/brewmaster-testing_games.txt | cut -d " " -f 2`; do find pool -name "$f*.deb" -exec reprepro includedeb brewmaster-testing {} \;; done
```

Something like that, among other tinkering. I think things will be repairable. Any missing packages or items just will need reported.

**Comment by oolongbrothers** [comment]
Ouch.
That sounds like that should cover everything though. Package lists look good from a quick browse.
I'll check the packages that I pull in, after work today. However I am only using `brewmaster-main` and `brewmaster-games`...

Thanks!

**Comment by oolongbrothers** [comment]
Hi again,

I went through my provisioning and most of the stuff I use seems to be there. However, I have found one package that I installed that's no longer there: `libretro-genesisplusgx`
Another one that caught my eye is `pcsx2`, that one is only there in 32 bit, which seems a bit weird. I'm not sure if it was like that since earlier.

**Comment by mdeguzis** [comment]
Ok, i'll have them back in soon. Check again in about an hour.

**Comment by mdeguzis** [comment]
done

**Comment by oolongbrothers** [comment]
Ah, great. Will check it out after work.
Sorry for what seems like slow responses, our time zone offset is not really helping :P

**Comment by oolongbrothers** [comment]
Right, sorry. I forgot about this. I can confirm that I can install `libretro-genesisplusgx` now. `pcsx2` is still only 32 bit, but I guess it was that way before.
So yeah, I think this is fixed. Anybody missing any packages can always open a new issue.

Thanks you!
//oolongbrothers

**Comment by mdeguzis** [comment]
np :)
