### ISSUE TITLE
dependency kodiplatform17 missing for kodi-peripheral-joystick

### ISSUE THREAD

**Issue by lasdem** [mdeguzis/SteamOS-Tools#171]
#### Your system information

* Steam client version: latest
* SteamOS version: Linux steamos 4.1.0-0.steamos.41-amd64 #1 SMP Debian 4.1.13-0+steamos15 (2016-11-22) x86_64 GNU/Linux
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
I freshly installed steamos brewmaster today, because I thought I needed to upgrade away from alchemist, because of end of support. One of my issues currently is that in Kodi 17 my XBox 360 wired controller is not registering at all. Even the controller setup screen does not register the button presses.  After some searching around I found that I probably need the "kodi-peripheral-joystick" package. But this package cannot be installed because of missing dependency: "kodiplatform17" 
The kodiplatform seems to be only found in the Sources, but not as a package. 
PS: For the controller problem I tried xpad and xboxdrv and both work in Steam, but not in Kodi.

#### Steps for reproducing this issue:
root@steamos:~# apt-get install kodi-peripheral-joystick
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 kodi-peripheral-joystick : Depends: libkodiplatform17 but it is not installable
E: Unable to correct problems, you have held broken packages.

root@steamos:~# aptitude show kodi-peripheral-joystick
Package: kodi-peripheral-joystick
State: not installed
Version: 1.3.2+git+bsos
Priority: extra
Section: libs
Maintainer: wsnipex <wsnipex@a1.net>
Architecture: amd64
Uncompressed Size: 786 k
Depends: libc6 (>= 2.17), libgcc1 (>= 1:4.1.1), libkodiplatform17, libp8-platform2, libpcre3 (>= 1:8.35), libpcrecpp0
         (>= 7.7), libstdc++6 (>= 4.9), libtinyxml2.6.2, libudev1 (>= 183)
Description: Joystick peripheral addon for Kodi
 Joystick peripheral addon for Kodi

root@steamos:~# apt-cache madison libkodiplatform17
kodiplatform | 17.0.0+git+bsos1 | http://packages.libregeek.org/steamos-tools/ brewmaster/main Sources

#### Progress Tracker (Please do not remove)

- [x] Investigate issue
- [x] Fix committed
- [ ] Confirmed Resolution

**Comment by mdeguzis** [comment]
Had to rebuild my repo from backup so figures I missed a few things. I will restore this soon.

**Comment by mdeguzis** [comment]
Ok, `apt-get update && apt-get install -f` and try again

**Comment by lasdem** [comment]
Thank you, it installed without problem now. =)

For everyone have the the Problem as me, installing this package did solve my underlying Problem that my XBox 360 wired controller did not work. But I had to go into Kodi (with keayboard) und configure the controller unter: System Settings -> Input -> Configure attached controllers.
Things to notice here: I did not Press the "Guide" button, because that takes you out of Kodi and into SteamOS, and both left and right trigger did not work (you should scroll down, because past the triggers are the Analog Sticks.

**Comment by lasdem** [comment]
PS: I highly appreciate your quick response and that you were able to help. 
Really, thank you very much and have a nice day =)
