### ISSUE TITLE
[Package Update Request] RetroArch 1.6.0+git20170606.b148ae8

### ISSUE THREAD

**Issue by flibitijibibo** [mdeguzis/SteamOS-Tools#173]
#### Your system information

* SteamOS version: 2.117
* Opted into SteamOS beta?: Yes

#### Please describe your issue in as much detail as possible:
In addition to RetroArch 1.6.0 being released, today there was a patch to the SDL2 joypad backend that fixed SDL_GameController support:

https://github.com/libretro/RetroArch/pull/5035

Without this patch, a whole bunch of controllers aren't usable (DualShock 4 was the one I found this bug with). If/When this package is updated, this patch is pretty much required to have controller support work without using a different backend.

#### Progress Tracker (Please do not remove)

- [x] Investigate issue
- [x] Fix committed
- [x] Confirmed Resolution

**Comment by mdeguzis** [comment]
Thanks for the heads up! I should be able to get to this tomorrow.

**Comment by mdeguzis** [comment]
Ouch, there has been 84 commits since that release. Ok, i'll just port the patch into the current release

**Comment by mdeguzis** [comment]
I was able to just pull the file and craft the patch with quilt. I patched it in before I created the tarball. Look for it soon.

**Comment by mdeguzis** [comment]
`retroarch_1.6.0+git20170606.f14473fd2~1` uploaded.

**Comment by flibitijibibo** [comment]
The update lgtm, thanks! But in a cruel series of timings, it turns out SteamOS 2.117 specifically breaks the DS4, so I can't test this for sure:

https://github.com/ValveSoftware/steamos_kernel/issues/53

If someone with a PS4 controller wants to try out the SDL2 backend and confirm it on 2.115 or lower we can mark this as done!

**Comment by flibitijibibo** [comment]
After fighting with the kernel for a bit I can now confirm that everything works as intended! This should be all set now.
