### ISSUE TITLE
[request] Suppress Chrome tab restore on exit from webapps

### ISSUE THREAD

**Issue by jonbitzen** [mdeguzis/SteamOS-Tools#175]
For some time I've found that when I use the steam button to exit the web app (I'm not sure how else to do it) the web app always starts the next time saying that Chrome exited irregularly, would I like to restore tabs.  I've found a solution for this issue that I'd like to recommend for the web app generator.  Below is a sample of my Netflix web app, with the fix highlighted:

```
#!/bin/sh

main()
{

  WIN_RES=$(DISPLAY=:0 xdpyinfo | grep dimensions | awk '{print $2}')
  COMMA_WIN_RES=$(echo $WIN_RES | awk '{sub(/x/, ","); print}')

  /usr/bin/Xephyr :15 -ac -screen $WIN_RES -fullscreen -host-cursor -once & XEPHYR_PID=$!

  # For some reason, the Xephyr window never gets populated with a value for the 
  # STEAM_GAME atom. It is possible to set the property manually though
  # This may not be necessary, see discussion under issue #60
  sleep 1s
  WINDOW_ID=$(xwininfo -root -children | grep "Xephyr" | awk '{print $1}')
  xprop -id $WINDOW_ID -f "STEAM_GAME" 32c -set "STEAM_GAME" 8000

  # start antimicro mouse control
  #mouse_control_disabled

#---------- ADD THESE TWO LINES TO GET RID OF THE TAB RESTORE AFTER EXITING --------
  sed -i 's/"exited_cleanly":false/"exited_cleanly":true/' ~/.config/google-chrome/Default/Preferences
  sed -i 's/exit_type":"Crashed/exit_type":"None/' ~/.config/google-chrome/Default/Preferences
#----------------------------------------------------------------------------------------------------------------------------------

  export DISPLAY=:15
  LD_PRELOAD= google-chrome-stable --kiosk www.netflix.com --window-size=$COMMA_WIN_RES &&

  sleep 1
  killall chrome
  killall antimicro
  kill $XEPHYR_PID

}

# start and log
rm -f /tmp/webapps_log.txt
main | tee /tmp/webapps_log.txt`
```

#### Your system information

* Steam client version:
* SteamOS version: 
* Opted into Steam client beta?: [Yes/No] 
* Opted into SteamOS beta?: [Yes/No] 
* Have you checked for updates in Settings > System?: [Yes/No]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Optional:Run `bash utilties/steamos-systeminfo-tool` from within the SteamOS-Tools repository directory and attach the resultant zip file.

#### Steps for reproducing this issue:

1. 
2. 
3. 

#### Progress Tracker (Please do not remove)

- [ ] Investigate issue
- [ ] Fix committed
- [ ] Confirmed Resolution

**Comment by mdeguzis** [comment]
I'll def take a look at this soon, thanks! For some control schemes, beyond using a Steam Controller, check the wiki, it as tons of info :)

https://github.com/mdeguzis/SteamOS-Tools/wiki/Web-Apps
