### ISSUE TITLE
Infinite loading screen when launching Windows games from BPM

### ISSUE THREAD

**Issue by YungDaVinci** [mdeguzis/SteamOS-Tools#176]
#### Your system information

* Steam client version:
* SteamOS version: 2
* Opted into Steam client beta?: [**Yes**/No] 
* Opted into SteamOS beta?: [**Yes**/No] 
* Have you checked for updates in Settings > System?: [**Yes**/No]

#### Please describe your issue in as much detail as possible:
Not sure if this was the right place to put this.
Using the method in the wiki to play Windows games from BPM just results in an infinite loading screen when launching the game. I can hear the game music sometimes but I can't control or see the game at all. At first the Steam overlay works for a little but after a while it won't show up anymore. I've tried this with 2 games so far.

#### Steps for reproducing this issue:
1. Follow [these steps](https://github.com/mdeguzis/SteamOS-Tools/wiki/Playing-Steam-(Windows)-Games-Using-PlayOnLinux)
2. Try to play the game
3. Infinite loading screen

#### Progress Tracker (Please do not remove)

- [ ] Investigate issue
- [ ] Fix committed
- [ ] Confirmed Resolution

**Comment by mdeguzis** [comment]
Please list a few games and I'll see if I have them to try to replicate your issue.

**Comment by YungDaVinci** [comment]
So far I've tried it with Sonic & All-Stars Racing Transformed, Pacman Championship Edition DX+, and Rayman Origins.

Rayman Origins bin file (the important parts):
```sh
# Define some Wine variables for use in the script.
export WINEPREFIX="/home/steam/.PlayOnLinux/wineprefix/Steam"
export WINEDEBUG="-all"
WINEVERSION="$HOME/.PlayOnLinux/wine/linux-x86/2.12-staging"

# Change LD_LIBRARY_PATH to include the lib directories for the version of wine that you are running.
# Please see: issues/115
export LD_LIBRARY_PATH="$WINEVERSION/lib:$WINEVERSION/lib64:$LD_LIBRARY_PATH"
export PATH="$WINEVERSION/bin:$PATH"

#Define Steam location and game location here.
# NOTE: GAME_DIR is not used with current method. Possibly remove?
STEAM_DIR="$WINEPREFIX/drive_c/Program Files/Steam"
GAME_APPID="207490"
GAME_DIR="GAME_DIR"
GAME_EXE="Rayman Origins.exe"
```

.desktop file:
```
[Desktop Entry]
Version=1.0
Name=Rayman Origins
GenericName=Game
Type=Application
Exec=/usr/bin/rayman
Icon=playonlinux
Categories=Game;
```

**Comment by YungDaVinci** [comment]
So randomly one time, Pac-Man decided it wanted to work. I didn't really do anything besides enable offline mode shortcuts. During the launch, i noticed that the Wine virtual desktop actually came up and launched the game, whereas other times the virtual desktop would flash on the screen, only to disappear and be replaced with the three loading bars. What is going on?

**Comment by YungDaVinci** [comment]
I fixed it. I looked through the script and the offending line appears to be this one:
```sh
# Allow a little sleep time so steamcompmgr uses the virtual deskop
# window.
sleep 3
```
I commented out that line and now it works beautifully. Well, aside from controller support. But I'll figure that out.
Guess I'll close this.
