### ISSUE TITLE
Playonlinux-script with skeleton-files are executed in background 

### ISSUE THREAD

**Issue by silelmot** [mdeguzis/SteamOS-Tools#177]
HEy there
after a long time a played arround with the playonlinux-skel-files again to make "overcooked" execute in steamos.
it does seem to run, but it is run in the background. steamos is showing the 3 loading-bar-animation ,
but i hear the starting sound of the game.
is this a focus problem only? how to get that fixed the best way? any ideas?

**Comment by mdeguzis** [comment]
Hmm, haven't run into that one yet. Is there a demo of this game to try?
