### ISSUE TITLE
Update Kodi to 17.6

### ISSUE THREAD

**Issue by ezelkow1** [mdeguzis/SteamOS-Tools#179]
#### Your system information

* Steam client version:
* SteamOS version: 
* Opted into Steam client beta?: [Yes/No] yes
* Opted into SteamOS beta?: [Yes/No] yes
* Have you checked for updates in Settings > System?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
The 'final' release of kodi17 is at 17.6 out now. Some previous versions included some linux specific fixes as well. Would be nice to have the final release of 17 available until 18 is workable

#### Progress Tracker (Please do not remove)

- [ ] Investigate issue
- [ ] Fix committed
- [ ] Confirmed Resolution

**Comment by mdeguzis** [comment]
Already reported, not possible until SteamOS moves to a Debian Stretch base. Kodi now uses required features of a newer GCC toolchain.
