### ISSUE TITLE
Suggestion: NetworkManager bump from Stretch

### ISSUE THREAD

**Issue by kramlat** [mdeguzis/SteamOS-Tools#180]
#### Your system information

* Steam client version:N/A
* SteamOS version: 2.x
* Opted into Steam client beta?: N/A
* Opted into SteamOS beta?: N/A
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
Apparently the version of NetworkManager installed in Vanilla SteamOS, which came from Jessie  (0.90.x) does not support VPN Config file import, thus making NordVPN unusable on SteamOS.
I propose a NetworkManager bump to 1.6.2-3 (version in Stretch) to add the missing feature, oh and I have already generated the package files, built against most recent update of SteamOS, and attached the deb files below:

[packages.zip.zip](https://github.com/mdeguzis/SteamOS-Tools/files/2345296/packages.zip.zip)
[packages-gtk.zip](https://github.com/mdeguzis/SteamOS-Tools/files/2345877/packages-gtk.zip)
[packages-modules.zip](https://github.com/mdeguzis/SteamOS-Tools/files/2346543/packages-modules.zip)

#### Progress Tracker (Please do not remove)

- [ ] Investigate issue
- [ ] Fix committed
- [ ] Confirmed Resolution

**Comment by mdeguzis** [comment]
Thanks! I'll try to get to this with the next week here.
